// Per-lesson teaching review: [plain model, senior reasoning checkpoint, lab scope/evidence].
export const TYPESCRIPT_EXECUTABLE_LESSONS = new Set([
  "0129", "0130", "0131", "0132", "0133", "0134", "0135", "0136", "0137", "0138",
  "0139", "0140", "0141", "0142", "0143", "0144", "0145", "0146", "0147", "0148",
  "0149", "0150", "0151", "0157", "0158", "0162"
]);
export const TYPESCRIPT_REVIEW = {
  "0126": ["The compiler checks a project selected by its configuration, not whatever files happen to be open in the editor.", "Pin the compiler and lockfile; compare CLI and editor versions before interpreting disagreement. A green checker is not a runtime test.", "Configuration exercise: create src/index.ts, install a pinned local TypeScript, and record version, showConfig, and noEmit results. JSON and shell lines belong in separate files/commands."],
  "0127": ["Parsing builds syntax; binding connects declarations to names; checking reasons about their types; emission produces output.", "transpileModule is a single-file transform, not a full semantic check or declaration build. Compare its output with a Program diagnostic for a wrong assignment.", "Tooling sketch: requires the typescript package and a Node project. Record AST, semantic diagnostic, JS, and declaration output separately; declaration: true in transpileModule does not supply a declaration build."],
  "0128": ["TypeScript deliberately accepts some programs whose runtime behavior can violate their annotations.", "An assertion on parsed JSON does not convert a number into a string. Explain what runtime validation would prove and what it would still not authorize.", "Intentional counterexample: first(users) compiles only without noUncheckedIndexedAccess. Enable that flag and explain its diagnostic; run the asserted JSON example and inspect the actual values."],
  "0129": ["Inference fills in missing types from values and context; widening keeps mutable values useful beyond their initial literal.", "Use annotations to stabilize public contracts, not every local variable. satisfies checks compatibility and can influence inference through context; it is not a runtime assertion.", "Type-only checks: the Equal/Expect aliases must compile. Change a mutable literal to as const and predict the diagnostic before inspecting inferred types."],
  "0139": ["readonly restricts writes through a typed reference. as const preserves literal information; neither freezes the JavaScript object.", "A mutable alias can still change a value exposed through a readonly view. Object.freeze is shallow too. Decide whether ownership, copying, or deeper freezing is actually required.", "Standalone type example. Add an expected-error write, run move on a tuple, and mutate a nested object through an existing mutable alias. Compare annotation, assertion, as const, and satisfies separately."],
  "0140": ["A useful generic connects types at more than one position, such as keeping each input item's extra fields in the returned Map.", "Constrain only capabilities the body needs. A map indexed by id also needs a duplicate policy: this example keeps the last item, not a magically unique record.", "Standalone example. Test duplicate IDs and preserved extra fields. choose now requires a nonempty tuple; prove that an empty input is rejected instead of hiding absence with !."],
  "0141": ["Inference gathers candidates from arguments and context; a constraint limits choices but cannot invent missing information.", "const type parameters preserve eligible inline literals, not information already widened in a variable. NoInfer controls candidate sources; it is available from TypeScript 5.4, not this workspace's 5.3 compiler.", "Shared generic mechanism, distinct exercise: compare inline literals, a string[] variable, and an explicit type argument. Redesign createStore so its item type comes from values, or supply both type arguments intentionally."],
  "0142": ["keyof names allowed keys, a type-position typeof captures a value's static type, and T[K] relates a selected key to its result.", "A generic key parameter preserves correlation that returning T[keyof T] would lose. Numeric and symbol keys need explicit treatment in string-only APIs.", "Standalone example. Call get with id and archived, assert their different result types, and reject a misspelled key. No runtime reflection is created by these type expressions."],
  "0143": ["A mapped type transforms a contract one key at a time; it does not loop over or modify runtime objects.", "The event-name mapping must concatenate on with Capitalize<K>, not intersect two incompatible strings. Homomorphic mappings can preserve modifiers; explicit modifiers change them.", "Standalone type example. Construct a ProjectEvents value with onName and onArchived handlers, reject onMissing, and prove MutablePatch removes readonly without changing the original Project contract."],
  "0144": ["A conditional type chooses a branch using assignability. A naked type parameter on the checked side distributes the operation over a union.", "Wrapping both sides in tuples asks about the union as a whole. never and any need dedicated examples; recursive types need a stopping condition and a checker-cost budget.", "Type-only example. Assert ElementOf<string[] | number[]> and NonDistributive<string | number>, then compare distributive and wrapped tests on never. Keep recursion shallow before considering deep utilities."],
  "0145": ["Template literal types construct sets of permitted strings from smaller sets.", "Two unions of sizes m and n can produce up to m times n names. A deeply recursive key-path type can cost more than the mistakes it prevents; generated declarations or shallow paths may be clearer.", "Shared type mechanism, distinct exercise: construct valid Changed names, reject a typo, and record checker timings when expanding the unions. A type does not parse arbitrary runtime strings."],
  "0146": ["Utility types are mechanical transformations; domain meaning must still be designed.", "Partial is shallow and is not a complete PATCH contract. Omit does not remove runtime secrets. ReturnType on an overloaded function uses its last signature, not overload resolution for a particular argument.", "Type-only example. Derive Partial and Pick, then compare a nested partial with an omitted field versus explicit clear. Reuse the tested PATCH lab from 0132 for runtime semantics."],
  "0147": ["A producer of dogs can supply animals; a consumer of all animals can safely consume dogs. Reversing either relationship is unsafe.", "strictFunctionTypes treats function-property parameters more strictly than method parameters. Mutable arrays retain unsound assignments for compatibility; readonly views prevent writes through that view, not all aliases.", "Standalone example. Add an expected-error dog-only function assigned to an animal consumer. Contrast method syntax and show how pushing through a mutable animal alias can contaminate a dog array."],
  "0148": ["A class has runtime construction and behavior as well as a static instance contract. An interface describes a contract without constructing anything.", "TypeScript private is a checker restriction; JavaScript # fields enforce a runtime access boundary. noImplicitOverride catches missing override markers, not behavioral substitutability.", "Class/brand sketch. Implement a concrete Repository and test missing/found results. Add an override mismatch under noImplicitOverride; compare composition before introducing a hierarchy."],
  "0149": ["A brand separates structurally identical values, such as two different kinds of string IDs, within checked code.", "The brand is not runtime evidence. The sample checks only a usr_ prefix; it does not establish format completeness, existence, ownership, or authorization. Serialize brands as their underlying value and revalidate on reentry.", "Standalone parser example. Reject nonstrings and wrong prefixes; add a negative UserId-to-ProjectId assignment. State the actual ID grammar before strengthening the parser."],
  "0150": ["A method decorator can replace a method while preserving its receiver, parameters, and return type.", "The sample finally runs when invocation returns, not when an async result settles. Standard and legacy decorator calling conventions differ; do not mix their configuration or assume legacy metadata behavior.", "Requires TypeScript 5+ standard decorator mode, without experimentalDecorators. Instantiate ProjectService, test receiver and thrown-error preservation, then compare Promise-returning methods before calling the log a duration measurement."],
  "0151": ["An enum can create a runtime object; a literal union is erased. An as-const object supplies runtime values from which a union can be derived.", "Numeric enums add reverse mappings; string enums do not. Exported const enums can embed a different version's values in consumers. Stable wire values need a compatibility policy independent of type syntax.", "Standalone parser. Test every allowed status plus null, inherited property names, and a typo. The key-membership parser works here because each key equals its value; do not generalize it to arbitrary lookup objects."],
  "0152": ["An import can be a type-checking edge, a runtime loading edge, or both. Explicit type imports disappear from emitted JavaScript.", "Erasing a type-only import also removes any runtime initialization you mistakenly expected from it. verbatimModuleSyntax exposes mismatches instead of silently rewriting incompatible module syntax.", "Multi-file exercise, not a standalone script: create project.ts with a real parser, package.json and tsconfig, then inspect emitted imports and run them with the chosen host."],
  "0153": ["Resolution models how a specific host finds a specifier. The editor finding a file does not guarantee the deployed host can load it.", "paths does not rewrite emitted specifiers. NodeNext and bundler mode model different host behavior; package conditions, extensions, and package type must agree with the actual entry point.", "Multi-file exercise: record traceResolution and run emitted JS without source aliases. Introduce a missing export condition or extension and diagnose the first mismatched edge."],
  "0154": ["A declaration file promises which values already exist at runtime; it supplies no implementation.", "An accidental script-global declaration can affect unrelated files. Module augmentation changes a known module's contract; it does not install a runtime feature. Choosing DOM libs cannot make browser APIs exist in Node.", "Multi-file declaration sketch. Supply the real implementation, test a consumer, then intentionally mismatch its result and show how a runtime test catches what declarations conceal."],
  "0155": ["A published library ships a runtime API and a declaration API that consumers must resolve to matching versions.", "A workspace source import can hide missing packaged files. exports conditions and declarations must agree; typesVersions is not a universal override when exports controls resolution.", "Packaging sketch. npm pack --dry-run lists files but does not create the tarball. Run npm pack, install that actual named archive in a clean consumer, and test public imports and runtime behavior."],
  "0156": ["Checked JavaScript allows types to be added incrementally through JSDoc without first changing runtime syntax.", "allowJs admits JavaScript; checkJs or ts-check reports its type issues. A JSDoc cast is still a trusted claim, so runtime parser tests remain essential during migration.", "JavaScript module, not a .ts lab. Use allowJs/checkJs with noEmit, test valid and invalid JSON, then rename one dependency leaf and compare emitted behavior before broad migration."],
  "0157": ["A parser converts uncertain input into a deliberately validated representation or a useful failure result.", "The example strips extras and trims names, but a string ownerId is only shape-valid. Schema inference helps keep types aligned; it does not choose business rules, error privacy, or authorization.", "Runnable parser checks cover good input, null, arrays, missing fields, blank names, and a wrong ownerId type. Extend with size limits and your domain's ID rules before service use."],
  "0158": ["Each external boundary brings uncertainty even when both applications are written in TypeScript.", "Do not trust an ownerId merely because it passes string validation. Derive identity from authentication or authorize delegation. Database rows, queue versions, environment strings, and AI output require different policies.", "Parser mechanism shared with 0157; integration exercise: add malformed JSON handling, unauthorized ownership, an old queue version, invalid environment data, and invalid model output. Document the rejection owner at every boundary."],
  "0159": ["Async types describe eventual values and iterator protocol slots, not timeouts, concurrency limits, or cancellation guarantees.", "The generator checks HTTP status and cancellation, but still needs a trusted URL policy, redirect controls, repeated-cursor detection, page/item limits, and a deadline. Same-origin cursor checks alone are not an SSRF defense.", "Network integration sketch: inject or stub fetch and test non-2xx responses, malformed pages, cancellation between yielded items, consumer break, and cursor loops. Bound total work before production use."],
  "0160": ["Generic props connect each row to its selection callback; they should not force callers to understand advanced types just to render a table.", "Row[keyof Row] is a union of column values, not a key-specific value. Use a mapped union or row-based renderer when correlation matters. A clickable row alone is not keyboard-accessible; this example uses a native button.", "TSX integration sketch requires pinned React and matching types. Test keyboard selection, empty data, stable keys, and renderer types. Add refs and reducer exercises separately; they are not implemented by this table."],
  "0161": ["Node executes JavaScript under a concrete module and process model; successful type checking does not guarantee loading or shutdown behavior.", "Aborting a controller is a signal, not a shutdown implementation. Stop admission, drain within a deadline, close owned resources, and preserve exit errors. Reject malformed configuration before binding a port.", "Service integration sketch: serve is an adapter the learner must implement. Requires Node types and matching ESM configuration. Test invalid configuration and SIGTERM with active work; record deadline and resource closure."],
  "0162": ["Type tests check what programs are accepted; runtime tests check what executed code actually does.", "An unused ts-expect-error detects a lost rejection, but it does not identify which diagnostic occurred. Narrow negative examples so an unrelated error cannot masquerade as the intended protection.", "Runnable type-test lab: first has a real implementation, the invalid call is in an uncalled checked function, and a runtime assertion verifies the first element. Compile emitted declarations from a separate consumer next."],
  "0163": ["target selects syntax transforms, lib describes assumed APIs, module chooses module output behavior, and moduleResolution models lookup.", "lib declarations are not polyfills. exclude limits initial discovery, not all imports; imported files may still enter the program. Give each environment and output directory a clear build owner.", "Configuration fragments, not TypeScript source. Supply actual per-environment module settings and source includes; inspect showConfig and explainFiles and run output on the oldest supported host."],
  "0164": ["Project references create an explicit build graph with declaration boundaries and reusable build state.", "A root reference list alone does not express server-to-domain dependencies. Each consuming project needs the appropriate references. Composite builds add artifact and invalidation costs; keep a single project when it is sufficient.", "Multi-project sketch: create every referenced directory and config, add consumer references, run tsc -b twice, change a domain export, and inspect which projects rebuild."],
  "0165": ["An AST node is a syntax occurrence; a symbol identifies declarations; a type is the checker's semantic view at a location.", "The sample is a syntax-policy scan of exported function declarations, not a complete public API analyzer. It misses exported arrows, re-exports, and some export forms. Do not call missing annotations correctness bugs automatically.", "Tooling sketch requires typescript and input files. Test direct functions, arrows, aliases, and re-exports; use the module's exports and checker if the requirement is the complete public API."],
  "0166": ["Compiler latency comes from discovering files, parsing, checking relationships, and maintaining project state; measure the dominant cost first.", "Compare clean and warm builds separately, using the same version and hardware. skipLibCheck may hide declaration conflicts; it is a trade-off, not a diagnosis. Trace files may reveal local paths and source details.", "Shell diagnostic recipe for an existing project. Record timings, files, instantiations, memory, and editor wait before and after one change; retain traces privately unless reviewed for disclosure."],
  "0167": ["A compiler upgrade can change inference, diagnostics, declaration compatibility, resolution, and emitted code.", "Pin versions, read the intervening release notes, classify failures, and test real consumers before rollout. A mass suppression hides migration work instead of resolving it.", "Review checklist, not test evidence. Replace every placeholder claim with a command result or artifact, compare public declarations and emitted JS, and document rollback and supported compiler versions."],
  "0168": ["Generated code is an untrusted contribution whose contracts, dependencies, and runtime behavior need the same scrutiny as other code.", "A type-correct implementation may still authorize the wrong tenant, leak secrets, or perform unbounded work. Ask what invariant each test proves and whether a malicious input could bypass it.", "Review exercise, not executable certification. Choose one generated change, test malformed input, cross-tenant access, timeout, and large payloads, and record provenance rather than marking checklist booleans true."],
  "0169": ["Keep business decisions separate from transport and vendor details; inject the capabilities the decision actually needs.", "A port is justified by a meaningful boundary, not by a rule to wrap every function. The sample requires an idempotencyKey parser, not the ownerId parser from the earlier lab; telemetry must not replace the business outcome by throwing in finally.", "Architecture sketch: implement matching parsing and adapters, test duplicate commands, cancellation, repository failure, and telemetry failure. Compare change cost against a direct implementation before adding abstractions."],
  "0170": ["The capstone joins type contracts with runtime validation, ownership, persistence, and operational behavior in one deployable slice.", "Sharing a DTO does not solve wire evolution, authorization, idempotency, or schema rollout. Choose one invariant at each boundary and demonstrate both its failure case and recovery behavior.", "Project assignment, not a finished application. Deliver a versioned request flow, authenticated ownership, durable idempotency, bounded model calls, validated outputs, trace evidence, type/runtime tests, and a mixed-version rollback rehearsal."]
};

export function typescriptReviewFor(lesson) {
  if (lesson.trackId !== "typescript") return undefined;
  return TYPESCRIPT_REVIEW[lesson.number] || [lesson.behindTheScenes || lesson.behind_the_scenes,
    lesson.interview, "Standalone lab with compiler-negative and runtime assertions. Run node scripts/check-typescript-lessons.mjs from the workspace. Predict the result before reading the checks; reconstruct the key distinction tomorrow."];
}

export function typescriptSourceFor(number) {
  if (number === "0160") return "https://react.dev/learn/typescript";
  if (number === "0164") return "https://www.typescriptlang.org/docs/handbook/project-references.html";
  if (number === "0166") return "https://github.com/microsoft/TypeScript/wiki/Performance";
  if (number === "0150") return "https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators";
  if (number >= "0152" && number <= "0155") return "https://www.typescriptlang.org/docs/handbook/modules/reference.html";
  if (number === "0143") return "https://www.typescriptlang.org/docs/handbook/2/mapped-types.html";
  if (number === "0144") return "https://www.typescriptlang.org/docs/handbook/2/conditional-types.html";
  if (number === "0146") return "https://www.typescriptlang.org/docs/handbook/utility-types.html";
  return "https://www.typescriptlang.org/docs/handbook/intro.html";
}
